# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' CheckPrimer
#'
#' blabla
#'
#' @param pr2 pr2 data.frame
#' @param primer1 vector of all possible primer 1 to consider
#' @param primer2 vector of all possible primer 2 to consider
#' @param l_min bla
#' @param l_max bla
#'
#' @export
#' @useDynLib PatPilr
#' @importFrom Rcpp sourceCpp
CheckPrimer <- function(pr2, primer1, primer2, l_min, l_max) {
    .Call('_PatPilr_CheckPrimer', PACKAGE = 'PatPilr', pr2, primer1, primer2, l_min, l_max)
}

